# Generated by Django 3.1.3 on 2021-02-07 10:32

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210201_1443'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='passport',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='angina_or_heart_attack',
        ),
        migrations.RemoveField(
            model_name='user',
            name='atrial_fibrillation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='user',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='diabets',
        ),
        migrations.RemoveField(
            model_name='user',
            name='district',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ethnicity',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='height',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kidney_disease',
        ),
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
        migrations.RemoveField(
            model_name='user',
            name='menopause',
        ),
        migrations.RemoveField(
            model_name='user',
            name='physical_activity',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pressure_treatment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rheumatoid_arthritis',
        ),
        migrations.RemoveField(
            model_name='user',
            name='smoking',
        ),
        migrations.RemoveField(
            model_name='user',
            name='town',
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_regular_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.CreateModel(
            name='RegularUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Card number')),
                ('language', models.CharField(choices=[('EN', 'English'), ('RU', 'Russian'), ('TR', 'Turkish'), ('AZ', 'Azerbaijan')], default='EN', max_length=50, null=True, verbose_name='Language')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='female', max_length=50, null=True, verbose_name='Gender')),
                ('height', models.IntegerField(null=True, verbose_name='Height(cm)')),
                ('blood_group', models.CharField(blank=True, choices=[('A RH+', 'A RH+'), ('A RH-', 'A RH-'), ('AB RH+', 'AB RH+'), ('AB RH-', 'AB RH-'), ('B RH+', 'B RH+'), ('B RH-', 'B RH-'), ('0 RH+', '0 RH+'), ('0 RH-', '0 RH-')], default='A RH+', max_length=50, null=True, verbose_name='Blood Group')),
                ('city2', models.CharField(blank=True, max_length=50, null=True, verbose_name='City*')),
                ('physical_activity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=50, null=True, verbose_name='Physical Activity')),
                ('smoking', models.CharField(blank=True, choices=[('Non-smoker', 'Non-smoker'), ('Ex-smoker', 'Ex-smoker'), ('Light-smoker', 'Light smoker (less than 10)'), ('Moderate-smoker', 'Moderate smoker (10 to 19)'), ('Heavy-smoker', 'Heavy smoker (20 or over)')], default='Non-smoker', max_length=50, null=True, verbose_name='Smoking')),
                ('diabets', models.CharField(blank=True, choices=[('None', 'None'), ('Type 1', 'Type 1'), ('Type 2', 'Type 2')], default='None', max_length=50, null=True, verbose_name='Diabets')),
                ('ethnicity', models.CharField(choices=[('White', 'White or not stated'), ('Indian', 'Indian'), ('Pakistani', 'Pakistani'), ('Bangladeshi', 'Bangladeshi'), ('Asian', 'Other Asian'), ('Caribbean', 'Black Caribbean'), ('African', 'Black African'), ('Chinese', 'Chinese'), ('Others', 'Others')], default='White', max_length=50, null=True, verbose_name='Ethnicity')),
                ('angina_or_heart_attack', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='ANGINA OR HEART ATTACK IN A 1ST DEGREE RELATIVE &lt;60?')),
                ('menopause', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='Menopause')),
                ('kidney_disease', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='Kidney Disease')),
                ('atrial_fibrillation', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='Arterial Fibrillation')),
                ('pressure_treatment', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='DO YOU GETTING PRESSURE TREATMENT?')),
                ('rheumatoid_arthritis', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='Rheumatoid Arthritis')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.country', verbose_name='Country')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.district', verbose_name='District')),
                ('town', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.town', verbose_name='Town/Village')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regular_user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificates', models.CharField(max_length=250)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
