# Generated by Django 3.1.3 on 2021-03-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210307_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorcategory',
            name='cat_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctorcategory',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('RU', 'Russian'), ('TR', 'Turkish'), ('AZ', 'Azerbaijan')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctorcategory',
            name='cat_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
